name: flask_sample

services:
  app:
    build:
      context: ./../
      dockerfile: ./Dockerfile
    volumes:
      # ホストマシンのディレクトリとコンテナ内のディレクトリを同期
      - ./../:/usr/src/flask_sample
    ports: 
      - "5000:5000"

  postgres_db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_sample
    volumes:
      - db-store:/var/lib/postgressql/data

volumes:
  db-store: